[project]
name = "agents-daemons"
version = "0.1.0"
description = "Agent Daemons"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=2.6.1",
]

[dependency-groups]
dev = [
    "ruff>=0.14.3",
]
